// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2t3VK7g1uvSSQKaf4eTzZ6qMrSIDyxLg',
    appId: '1:240342413009:web:2d63254b4b2e4df9f09ff0',
    messagingSenderId: '240342413009',
    projectId: 'gobook-app',
    authDomain: 'gobook-app.firebaseapp.com',
    storageBucket: 'gobook-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qJCWL5tnQkCRNbhE2SyjKyIW4yDFnCU',
    appId: '1:240342413009:android:a6c51862617ed23bf09ff0',
    messagingSenderId: '240342413009',
    projectId: 'gobook-app',
    storageBucket: 'gobook-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3BtoUHeKZxp5aIp0gzPqDrmV-Fw3pK1U',
    appId: '1:240342413009:ios:810b8612be2f4a51f09ff0',
    messagingSenderId: '240342413009',
    projectId: 'gobook-app',
    storageBucket: 'gobook-app.appspot.com',
    iosBundleId: 'com.sudarlife.gobook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3BtoUHeKZxp5aIp0gzPqDrmV-Fw3pK1U',
    appId: '1:240342413009:ios:07571f91162e5bcdf09ff0',
    messagingSenderId: '240342413009',
    projectId: 'gobook-app',
    storageBucket: 'gobook-app.appspot.com',
    iosBundleId: 'com.sudarlife.gobook.RunnerTests',
  );
}
